### ISSUE TITLE
Demo project illustrates API usage

### ISSUE THREAD

**Issue by benoitbryon** [novapost/django-docusign#4]
... and it is tested!

**Comment by danaev** [comment]
Hello , I am trying to check out the demo. How exactly am I doing that? I am trying to run python manage.py runserver and I get an error `ImportError: No module named None.settings .`
Do I have to install something extra? I have clone the repo and I have installed django-docusign in a virtualenv.

**Comment by zebuline** [comment]
@danaev try `django-docusign-demo runserver` or `make serve`

**Comment by danaev** [comment]
`make serve` worked ! thanks!
